backend:
  name: github
  repo: aurora-digital/auroradigital.co
  branch: netlify-cms
media_folder: static/assets
public_folder: assets
publish_mode: editorial_workflow
media_folder_relative: true
collections:
  - name: "blog"
    label: "Blog"
    folder: "blog/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{author}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "featuredImage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
